### ISSUE TITLE
why using peerDependencies instead of DevDependencies?

### ISSUE THREAD

**Issue by LastStranger** [mryechkin/eslint-config-acme#1]
I know NPM7.X will auto-install peerDependdencies, but for NPM7.X early version users, they have to install those by themselves, which is not convenient, and I use Pnpm has the same issue, what's the good of using peerDependencies?

**Comment by mryechkin** [comment]
Because there is no executable code in shared configs (it's essentially just exporting a plain object), so it wouldn't make sense to package a bunch of dependencies with it. Users are expected to have ESLint and the other plugins installed in the consuming project, which is exactly what the peerDependencies field is for.

See these issues for more details:

https://github.com/eslint/eslint/issues/3458

https://github.com/eslint/eslint/issues/2518
